### ISSUE TITLE
Suggestion: Using xkcd.com/archive

### ISSUE THREAD

**Issue by BlitzKraft** [Rhnbmpl/xkcd_downloader#1]
The archive lists all the comics published to date. This might help with code readability. I see the loop incrementing the url index. Also help reduce the number of requests to the server.

**Comment by Rhnbmpl** [comment]
Yeah using links form archive is better but I wanted to try it with the normal method. Anyways, I will add the archive method and put my current method as the backup in case the archive page fails. Thanks for the suggestion because I did not know about the archive page
